server:
  port: 8080
  servlet:
    contextPath: "/mercadona"
logging:
  level:
    org:
      springframework:
        jdbc:
          datasource:
            init:
              ScriptUtils: "debug"
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:productsdb"
  jpa:
    hibernate:
      ddl-auto: "none"
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
---
spring:
  config:
    activate:
      on-profile: "desarrollo"
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: "preproduccion"
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: "produccion"
server:
  port: 8123